### PR TITLE
replaced asserts with AssertionError

### PR DESCRIPTION
**Pull request by black-snow**
Replaced all assert-statements with if(!statement) throw new
AssertionError() using Android Studio’s automatic replacement.

### CODE REVIEW

**Comment by black-snow** [comment]
See #10

**Comment by peternied** [comment]
Thanks for the pull request, but could you retarget the dev branch instead of master?

**Comment by black-snow** [comment]
phew, okay, I'll look into that tomorrow

**Comment by black-snow** [comment]
Thanks for the merge.

**Comment by marcote** [comment]
@black-snow no, thanks to you :+1:

**Pull request merged**
